HEADERS += \
    ../../VNA_embedded/Application/Communication/Protocol.hpp \
    ../../VNA_embedded/Application/Communication/PacketConstants.h \
    Calibration/Eigen/Cholesky \
    Calibration/Eigen/CholmodSupport \
    Calibration/Eigen/Core \
    Calibration/Eigen/Dense \
    Calibration/Eigen/Eigen \
    Calibration/Eigen/Eigenvalues \
    Calibration/Eigen/Geometry \
    Calibration/Eigen/Householder \
    Calibration/Eigen/IterativeLinearSolvers \
    Calibration/Eigen/Jacobi \
    Calibration/Eigen/KLUSupport \
    Calibration/Eigen/LU \
    Calibration/Eigen/MetisSupport \
    Calibration/Eigen/OrderingMethods \
    Calibration/Eigen/PaStiXSupport \
    Calibration/Eigen/PardisoSupport \
    Calibration/Eigen/QR \
    Calibration/Eigen/QtAlignedMalloc \
    Calibration/Eigen/SPQRSupport \
    Calibration/Eigen/SVD \
    Calibration/Eigen/Sparse \
    Calibration/Eigen/SparseCholesky \
    Calibration/Eigen/SparseCore \
    Calibration/Eigen/SparseLU \
    Calibration/Eigen/SparseQR \
    Calibration/Eigen/StdDeque \
    Calibration/Eigen/StdList \
    Calibration/Eigen/StdVector \
    Calibration/Eigen/SuperLUSupport \
    Calibration/Eigen/UmfPackSupport \
    Calibration/Eigen/src/Cholesky/LDLT.h \
    Calibration/Eigen/src/Cholesky/LLT.h \
    Calibration/Eigen/src/Cholesky/LLT_LAPACKE.h \
    Calibration/Eigen/src/CholmodSupport/CholmodSupport.h \
    Calibration/Eigen/src/Core/ArithmeticSequence.h \
    Calibration/Eigen/src/Core/Array.h \
    Calibration/Eigen/src/Core/ArrayBase.h \
    Calibration/Eigen/src/Core/ArrayWrapper.h \
    Calibration/Eigen/src/Core/Assign.h \
    Calibration/Eigen/src/Core/AssignEvaluator.h \
    Calibration/Eigen/src/Core/Assign_MKL.h \
    Calibration/Eigen/src/Core/BandMatrix.h \
    Calibration/Eigen/src/Core/Block.h \
    Calibration/Eigen/src/Core/BooleanRedux.h \
    Calibration/Eigen/src/Core/CommaInitializer.h \
    Calibration/Eigen/src/Core/ConditionEstimator.h \
    Calibration/Eigen/src/Core/CoreEvaluators.h \
    Calibration/Eigen/src/Core/CoreIterators.h \
    Calibration/Eigen/src/Core/CwiseBinaryOp.h \
    Calibration/Eigen/src/Core/CwiseNullaryOp.h \
    Calibration/Eigen/src/Core/CwiseTernaryOp.h \
    Calibration/Eigen/src/Core/CwiseUnaryOp.h \
    Calibration/Eigen/src/Core/CwiseUnaryView.h \
    Calibration/Eigen/src/Core/DenseBase.h \
    Calibration/Eigen/src/Core/DenseCoeffsBase.h \
    Calibration/Eigen/src/Core/DenseStorage.h \
    Calibration/Eigen/src/Core/Diagonal.h \
    Calibration/Eigen/src/Core/DiagonalMatrix.h \
    Calibration/Eigen/src/Core/DiagonalProduct.h \
    Calibration/Eigen/src/Core/Dot.h \
    Calibration/Eigen/src/Core/EigenBase.h \
    Calibration/Eigen/src/Core/ForceAlignedAccess.h \
    Calibration/Eigen/src/Core/Fuzzy.h \
    Calibration/Eigen/src/Core/GeneralProduct.h \
    Calibration/Eigen/src/Core/GenericPacketMath.h \
    Calibration/Eigen/src/Core/GlobalFunctions.h \
    Calibration/Eigen/src/Core/IO.h \
    Calibration/Eigen/src/Core/IndexedView.h \
    Calibration/Eigen/src/Core/Inverse.h \
    Calibration/Eigen/src/Core/Map.h \
    Calibration/Eigen/src/Core/MapBase.h \
    Calibration/Eigen/src/Core/MathFunctions.h \
    Calibration/Eigen/src/Core/MathFunctionsImpl.h \
    Calibration/Eigen/src/Core/Matrix.h \
    Calibration/Eigen/src/Core/MatrixBase.h \
    Calibration/Eigen/src/Core/NestByValue.h \
    Calibration/Eigen/src/Core/NoAlias.h \
    Calibration/Eigen/src/Core/NumTraits.h \
    Calibration/Eigen/src/Core/PartialReduxEvaluator.h \
    Calibration/Eigen/src/Core/PermutationMatrix.h \
    Calibration/Eigen/src/Core/PlainObjectBase.h \
    Calibration/Eigen/src/Core/Product.h \
    Calibration/Eigen/src/Core/ProductEvaluators.h \
    Calibration/Eigen/src/Core/Random.h \
    Calibration/Eigen/src/Core/Redux.h \
    Calibration/Eigen/src/Core/Ref.h \
    Calibration/Eigen/src/Core/Replicate.h \
    Calibration/Eigen/src/Core/Reshaped.h \
    Calibration/Eigen/src/Core/ReturnByValue.h \
    Calibration/Eigen/src/Core/Reverse.h \
    Calibration/Eigen/src/Core/Select.h \
    Calibration/Eigen/src/Core/SelfAdjointView.h \
    Calibration/Eigen/src/Core/SelfCwiseBinaryOp.h \
    Calibration/Eigen/src/Core/Solve.h \
    Calibration/Eigen/src/Core/SolveTriangular.h \
    Calibration/Eigen/src/Core/SolverBase.h \
    Calibration/Eigen/src/Core/StableNorm.h \
    Calibration/Eigen/src/Core/StlIterators.h \
    Calibration/Eigen/src/Core/Stride.h \
    Calibration/Eigen/src/Core/Swap.h \
    Calibration/Eigen/src/Core/Transpose.h \
    Calibration/Eigen/src/Core/Transpositions.h \
    Calibration/Eigen/src/Core/TriangularMatrix.h \
    Calibration/Eigen/src/Core/VectorBlock.h \
    Calibration/Eigen/src/Core/VectorwiseOp.h \
    Calibration/Eigen/src/Core/Visitor.h \
    Calibration/Eigen/src/Core/arch/AVX/Complex.h \
    Calibration/Eigen/src/Core/arch/AVX/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/AVX/PacketMath.h \
    Calibration/Eigen/src/Core/arch/AVX/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/AVX512/Complex.h \
    Calibration/Eigen/src/Core/arch/AVX512/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/AVX512/PacketMath.h \
    Calibration/Eigen/src/Core/arch/AVX512/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/AltiVec/Complex.h \
    Calibration/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/AltiVec/MatrixProduct.h \
    Calibration/Eigen/src/Core/arch/AltiVec/MatrixProductCommon.h \
    Calibration/Eigen/src/Core/arch/AltiVec/MatrixProductMMA.h \
    Calibration/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    Calibration/Eigen/src/Core/arch/CUDA/Complex.h \
    Calibration/Eigen/src/Core/arch/Default/BFloat16.h \
    Calibration/Eigen/src/Core/arch/Default/ConjHelper.h \
    Calibration/Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h \
    Calibration/Eigen/src/Core/arch/Default/GenericPacketMathFunctionsFwd.h \
    Calibration/Eigen/src/Core/arch/Default/Half.h \
    Calibration/Eigen/src/Core/arch/Default/Settings.h \
    Calibration/Eigen/src/Core/arch/Default/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/GPU/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/GPU/PacketMath.h \
    Calibration/Eigen/src/Core/arch/GPU/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/HIP/hcc/math_constants.h \
    Calibration/Eigen/src/Core/arch/MSA/Complex.h \
    Calibration/Eigen/src/Core/arch/MSA/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/MSA/PacketMath.h \
    Calibration/Eigen/src/Core/arch/NEON/Complex.h \
    Calibration/Eigen/src/Core/arch/NEON/GeneralBlockPanelKernel.h \
    Calibration/Eigen/src/Core/arch/NEON/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/NEON/PacketMath.h \
    Calibration/Eigen/src/Core/arch/NEON/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/SSE/Complex.h \
    Calibration/Eigen/src/Core/arch/SSE/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/SSE/PacketMath.h \
    Calibration/Eigen/src/Core/arch/SSE/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/SVE/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/SVE/PacketMath.h \
    Calibration/Eigen/src/Core/arch/SVE/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/SYCL/InteropHeaders.h \
    Calibration/Eigen/src/Core/arch/SYCL/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/SYCL/PacketMath.h \
    Calibration/Eigen/src/Core/arch/SYCL/SyclMemoryModel.h \
    Calibration/Eigen/src/Core/arch/SYCL/TypeCasting.h \
    Calibration/Eigen/src/Core/arch/ZVector/Complex.h \
    Calibration/Eigen/src/Core/arch/ZVector/MathFunctions.h \
    Calibration/Eigen/src/Core/arch/ZVector/PacketMath.h \
    Calibration/Eigen/src/Core/functors/AssignmentFunctors.h \
    Calibration/Eigen/src/Core/functors/BinaryFunctors.h \
    Calibration/Eigen/src/Core/functors/NullaryFunctors.h \
    Calibration/Eigen/src/Core/functors/StlFunctors.h \
    Calibration/Eigen/src/Core/functors/TernaryFunctors.h \
    Calibration/Eigen/src/Core/functors/UnaryFunctors.h \
    Calibration/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    Calibration/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    Calibration/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    Calibration/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    Calibration/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    Calibration/Eigen/src/Core/products/GeneralMatrixVector.h \
    Calibration/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    Calibration/Eigen/src/Core/products/Parallelizer.h \
    Calibration/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    Calibration/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    Calibration/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    Calibration/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    Calibration/Eigen/src/Core/products/SelfadjointProduct.h \
    Calibration/Eigen/src/Core/products/SelfadjointRank2Update.h \
    Calibration/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    Calibration/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    Calibration/Eigen/src/Core/products/TriangularMatrixVector.h \
    Calibration/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    Calibration/Eigen/src/Core/products/TriangularSolverMatrix.h \
    Calibration/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    Calibration/Eigen/src/Core/products/TriangularSolverVector.h \
    Calibration/Eigen/src/Core/util/BlasUtil.h \
    Calibration/Eigen/src/Core/util/ConfigureVectorization.h \
    Calibration/Eigen/src/Core/util/Constants.h \
    Calibration/Eigen/src/Core/util/DisableStupidWarnings.h \
    Calibration/Eigen/src/Core/util/ForwardDeclarations.h \
    Calibration/Eigen/src/Core/util/IndexedViewHelper.h \
    Calibration/Eigen/src/Core/util/IntegralConstant.h \
    Calibration/Eigen/src/Core/util/MKL_support.h \
    Calibration/Eigen/src/Core/util/Macros.h \
    Calibration/Eigen/src/Core/util/Memory.h \
    Calibration/Eigen/src/Core/util/Meta.h \
    Calibration/Eigen/src/Core/util/NonMPL2.h \
    Calibration/Eigen/src/Core/util/ReenableStupidWarnings.h \
    Calibration/Eigen/src/Core/util/ReshapedHelper.h \
    Calibration/Eigen/src/Core/util/StaticAssert.h \
    Calibration/Eigen/src/Core/util/SymbolicIndex.h \
    Calibration/Eigen/src/Core/util/XprHelper.h \
    Calibration/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    Calibration/Eigen/src/Eigenvalues/ComplexSchur.h \
    Calibration/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    Calibration/Eigen/src/Eigenvalues/EigenSolver.h \
    Calibration/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    Calibration/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    Calibration/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    Calibration/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    Calibration/Eigen/src/Eigenvalues/RealQZ.h \
    Calibration/Eigen/src/Eigenvalues/RealSchur.h \
    Calibration/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    Calibration/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    Calibration/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    Calibration/Eigen/src/Eigenvalues/Tridiagonalization.h \
    Calibration/Eigen/src/Geometry/AlignedBox.h \
    Calibration/Eigen/src/Geometry/AngleAxis.h \
    Calibration/Eigen/src/Geometry/EulerAngles.h \
    Calibration/Eigen/src/Geometry/Homogeneous.h \
    Calibration/Eigen/src/Geometry/Hyperplane.h \
    Calibration/Eigen/src/Geometry/OrthoMethods.h \
    Calibration/Eigen/src/Geometry/ParametrizedLine.h \
    Calibration/Eigen/src/Geometry/Quaternion.h \
    Calibration/Eigen/src/Geometry/Rotation2D.h \
    Calibration/Eigen/src/Geometry/RotationBase.h \
    Calibration/Eigen/src/Geometry/Scaling.h \
    Calibration/Eigen/src/Geometry/Transform.h \
    Calibration/Eigen/src/Geometry/Translation.h \
    Calibration/Eigen/src/Geometry/Umeyama.h \
    Calibration/Eigen/src/Geometry/arch/Geometry_SIMD.h \
    Calibration/Eigen/src/Householder/BlockHouseholder.h \
    Calibration/Eigen/src/Householder/Householder.h \
    Calibration/Eigen/src/Householder/HouseholderSequence.h \
    Calibration/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    Calibration/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    Calibration/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    Calibration/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    Calibration/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    Calibration/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    Calibration/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    Calibration/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    Calibration/Eigen/src/Jacobi/Jacobi.h \
    Calibration/Eigen/src/KLUSupport/KLUSupport.h \
    Calibration/Eigen/src/LU/Determinant.h \
    Calibration/Eigen/src/LU/FullPivLU.h \
    Calibration/Eigen/src/LU/InverseImpl.h \
    Calibration/Eigen/src/LU/PartialPivLU.h \
    Calibration/Eigen/src/LU/PartialPivLU_LAPACKE.h \
    Calibration/Eigen/src/LU/arch/InverseSize4.h \
    Calibration/Eigen/src/MetisSupport/MetisSupport.h \
    Calibration/Eigen/src/OrderingMethods/Amd.h \
    Calibration/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    Calibration/Eigen/src/OrderingMethods/Ordering.h \
    Calibration/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    Calibration/Eigen/src/PardisoSupport/PardisoSupport.h \
    Calibration/Eigen/src/QR/ColPivHouseholderQR.h \
    Calibration/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    Calibration/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    Calibration/Eigen/src/QR/FullPivHouseholderQR.h \
    Calibration/Eigen/src/QR/HouseholderQR.h \
    Calibration/Eigen/src/QR/HouseholderQR_LAPACKE.h \
    Calibration/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    Calibration/Eigen/src/SVD/BDCSVD.h \
    Calibration/Eigen/src/SVD/JacobiSVD.h \
    Calibration/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    Calibration/Eigen/src/SVD/SVDBase.h \
    Calibration/Eigen/src/SVD/UpperBidiagonalization.h \
    Calibration/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    Calibration/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    Calibration/Eigen/src/SparseCore/AmbiVector.h \
    Calibration/Eigen/src/SparseCore/CompressedStorage.h \
    Calibration/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    Calibration/Eigen/src/SparseCore/MappedSparseMatrix.h \
    Calibration/Eigen/src/SparseCore/SparseAssign.h \
    Calibration/Eigen/src/SparseCore/SparseBlock.h \
    Calibration/Eigen/src/SparseCore/SparseColEtree.h \
    Calibration/Eigen/src/SparseCore/SparseCompressedBase.h \
    Calibration/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    Calibration/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    Calibration/Eigen/src/SparseCore/SparseDenseProduct.h \
    Calibration/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    Calibration/Eigen/src/SparseCore/SparseDot.h \
    Calibration/Eigen/src/SparseCore/SparseFuzzy.h \
    Calibration/Eigen/src/SparseCore/SparseMap.h \
    Calibration/Eigen/src/SparseCore/SparseMatrix.h \
    Calibration/Eigen/src/SparseCore/SparseMatrixBase.h \
    Calibration/Eigen/src/SparseCore/SparsePermutation.h \
    Calibration/Eigen/src/SparseCore/SparseProduct.h \
    Calibration/Eigen/src/SparseCore/SparseRedux.h \
    Calibration/Eigen/src/SparseCore/SparseRef.h \
    Calibration/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    Calibration/Eigen/src/SparseCore/SparseSolverBase.h \
    Calibration/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    Calibration/Eigen/src/SparseCore/SparseTranspose.h \
    Calibration/Eigen/src/SparseCore/SparseTriangularView.h \
    Calibration/Eigen/src/SparseCore/SparseUtil.h \
    Calibration/Eigen/src/SparseCore/SparseVector.h \
    Calibration/Eigen/src/SparseCore/SparseView.h \
    Calibration/Eigen/src/SparseCore/TriangularSolver.h \
    Calibration/Eigen/src/SparseLU/SparseLU.h \
    Calibration/Eigen/src/SparseLU/SparseLUImpl.h \
    Calibration/Eigen/src/SparseLU/SparseLU_Memory.h \
    Calibration/Eigen/src/SparseLU/SparseLU_Structs.h \
    Calibration/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    Calibration/Eigen/src/SparseLU/SparseLU_Utils.h \
    Calibration/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    Calibration/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    Calibration/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    Calibration/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    Calibration/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    Calibration/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    Calibration/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    Calibration/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    Calibration/Eigen/src/SparseLU/SparseLU_pivotL.h \
    Calibration/Eigen/src/SparseLU/SparseLU_pruneL.h \
    Calibration/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    Calibration/Eigen/src/SparseQR/SparseQR.h \
    Calibration/Eigen/src/StlSupport/StdDeque.h \
    Calibration/Eigen/src/StlSupport/StdList.h \
    Calibration/Eigen/src/StlSupport/StdVector.h \
    Calibration/Eigen/src/StlSupport/details.h \
    Calibration/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    Calibration/Eigen/src/UmfPackSupport/UmfPackSupport.h \
    Calibration/Eigen/src/misc/Image.h \
    Calibration/Eigen/src/misc/Kernel.h \
    Calibration/Eigen/src/misc/RealSvd2x2.h \
    Calibration/Eigen/src/misc/blas.h \
    Calibration/Eigen/src/misc/lapack.h \
    Calibration/Eigen/src/misc/lapacke.h \
    Calibration/Eigen/src/misc/lapacke_mangling.h \
    Calibration/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    Calibration/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    Calibration/Eigen/src/plugins/BlockMethods.h \
    Calibration/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    Calibration/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    Calibration/Eigen/src/plugins/IndexedViewMethods.h \
    Calibration/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    Calibration/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    Calibration/Eigen/src/plugins/ReshapedMethods.h \
    Calibration/LibreCAL/caldevice.h \
    Calibration/LibreCAL/librecaldialog.h \
    Calibration/LibreCAL/usbdevice.h \
    Calibration/calibration.h \
    Calibration/calibrationmeasurement.h \
    Calibration/calkit.h \
    Calibration/calkitdialog.h \
    Calibration/calstandard.h \
    Calibration/manualcalibrationdialog.h \
    CustomWidgets/colorpickerbutton.h \
    CustomWidgets/csvimport.h \
    CustomWidgets/informationbox.h \
    CustomWidgets/jsonpickerdialog.h \
    CustomWidgets/siunitedit.h \
    CustomWidgets/tilewidget.h \
    CustomWidgets/toggleswitch.h \
    CustomWidgets/touchstoneimport.h \
    CustomWidgets/tracesetselector.h \
    Device/LibreVNA/Compound/compounddevice.h \
    Device/LibreVNA/Compound/compounddeviceeditdialog.h \
    Device/LibreVNA/Compound/compounddriver.h \
    Device/LibreVNA/amplitudecaldialog.h \
    Device/LibreVNA/deviceconfigurationdialogv1.h \
    Device/LibreVNA/deviceconfigurationdialogvfe.h \
    Device/LibreVNA/deviceconfigurationdialogvff.h \
    Device/LibreVNA/devicepacketlog.h \
    Device/LibreVNA/devicepacketlogview.h \
    Device/LibreVNA/firmwareupdatedialog.h \
    Device/LibreVNA/frequencycaldialog.h \
    Device/LibreVNA/librevnadriver.h \
    Device/LibreVNA/librevnatcpdriver.h \
    Device/LibreVNA/librevnausbdriver.h \
    Device/LibreVNA/manualcontroldialogV1.h \
    Device/LibreVNA/manualcontroldialogvfe.h \
    Device/LibreVNA/manualcontroldialogvff.h \
    Device/LibreVNA/receivercaldialog.h \
    Device/LibreVNA/sourcecaldialog.h \
    Device/SNA5000A/sna5000adriver.h \
    Device/SSA3000X/ssa3000xdriver.h \
    Device/devicedriver.h \
    Device/devicelog.h \
    Device/devicetcpdriver.h \
    Device/tracedifferencegenerator.h \
    FieldMeasurement/fieldmeasurement.h \
    FieldMeasurement/fieldmeasurementwidget.h \
    Generator/generator.h \
    Generator/signalgenwidget.h \
    SpectrumAnalyzer/spectrumanalyzer.h \
    SpectrumAnalyzer/tracewidgetsa.h \
    Tools/eseries.h \
    Tools/impedancematchdialog.h \
    Tools/mixedmodeconversion.h \
    Tools/parameters.h \
    Traces/Marker/marker.h \
    Traces/Marker/markergroup.h \
    Traces/Marker/markermodel.h \
    Traces/Marker/markerwidget.h \
    Traces/Math/dft.h \
    Traces/Math/expression.h \
    Traces/Math/medianfilter.h \
    Traces/Math/parser/mpCompat.h \
    Traces/Math/parser/mpDefines.h \
    Traces/Math/parser/mpError.h \
    Traces/Math/parser/mpFuncCmplx.h \
    Traces/Math/parser/mpFuncCommon.h \
    Traces/Math/parser/mpFuncMatrix.h \
    Traces/Math/parser/mpFuncNonCmplx.h \
    Traces/Math/parser/mpFuncStr.h \
    Traces/Math/parser/mpFwdDecl.h \
    Traces/Math/parser/mpICallback.h \
    Traces/Math/parser/mpIOprt.h \
    Traces/Math/parser/mpIPackage.h \
    Traces/Math/parser/mpIPrecedence.h \
    Traces/Math/parser/mpIToken.h \
    Traces/Math/parser/mpIValReader.h \
    Traces/Math/parser/mpIValue.h \
    Traces/Math/parser/mpIfThenElse.h \
    Traces/Math/parser/mpMatrix.h \
    Traces/Math/parser/mpMatrixError.h \
    Traces/Math/parser/mpOprtBinAssign.h \
    Traces/Math/parser/mpOprtBinCommon.h \
    Traces/Math/parser/mpOprtCmplx.h \
    Traces/Math/parser/mpOprtIndex.h \
    Traces/Math/parser/mpOprtMatrix.h \
    Traces/Math/parser/mpOprtNonCmplx.h \
    Traces/Math/parser/mpOprtPostfixCommon.h \
    Traces/Math/parser/mpPackageCmplx.h \
    Traces/Math/parser/mpPackageCommon.h \
    Traces/Math/parser/mpPackageMatrix.h \
    Traces/Math/parser/mpPackageNonCmplx.h \
    Traces/Math/parser/mpPackageStr.h \
    Traces/Math/parser/mpPackageUnit.h \
    Traces/Math/parser/mpParser.h \
    Traces/Math/parser/mpParserBase.h \
    Traces/Math/parser/mpParserMessageProvider.h \
    Traces/Math/parser/mpRPN.h \
    Traces/Math/parser/mpScriptTokens.h \
    Traces/Math/parser/mpStack.h \
    Traces/Math/parser/mpTest.h \
    Traces/Math/parser/mpTokenReader.h \
    Traces/Math/parser/mpTypes.h \
    Traces/Math/parser/mpValReader.h \
    Traces/Math/parser/mpValue.h \
    Traces/Math/parser/mpValueCache.h \
    Traces/Math/parser/mpVariable.h \
    Traces/Math/parser/suSortPred.h \
    Traces/Math/parser/suStringTokens.h \
    Traces/Math/parser/utGeneric.h \
    Traces/Math/tdr.h \
    Traces/Math/timegate.h \
    Traces/Math/tracemath.h \
    Traces/Math/windowfunction.h \
    Traces/eyediagramplot.h \
    Traces/fftcomplex.h \
    Traces/sparamtraceselector.h \
    Traces/trace.h \
    Traces/traceaxis.h \
    Traces/tracecsvexport.h \
    Traces/traceeditdialog.h \
    Traces/traceimportdialog.h \
    Traces/tracemodel.h \
    Traces/traceplot.h \
    Traces/tracesmithchart.h \
    Traces/tracetouchstoneexport.h \
    Traces/tracewaterfall.h \
    Traces/tracewidget.h \
    Traces/tracexyplot.h \
    Traces/tracepolar.h \
    Traces/waterfallaxisdialog.h \
    Traces/xyplotaxisdialog.h \
    Traces/tracepolarchart.h \
    Util/prbs.h \
    Util/qpointervariant.h \
    Util/usbinbuffer.h \
    Util/util.h \
    Util/app_common.h \
    VNA/Deembedding/deembedding.h \
    VNA/Deembedding/deembeddingdialog.h \
    VNA/Deembedding/deembeddingoption.h \
    VNA/Deembedding/impedancerenormalization.h \
    VNA/Deembedding/manualdeembeddingdialog.h \
    VNA/Deembedding/matchingnetwork.h \
    VNA/Deembedding/portextension.h \
    VNA/Deembedding/twothru.h \
    VNA/tracewidgetvna.h \
    VNA/vna.h \
    about.h \
    appwindow.h \
    averaging.h \
    csv.h \
    json.hpp \
    modehandler.h \
    mode.h \
    modewindow.h \
    preferences.h \
    savable.h \
    scpi.h \
    streamingserver.h \
    tcpserver.h \
    touchstone.h \
    unit.h

SOURCES += \
    ../../VNA_embedded/Application/Communication/Protocol.cpp \
    Calibration/LibreCAL/caldevice.cpp \
    Calibration/LibreCAL/librecaldialog.cpp \
    Calibration/LibreCAL/usbdevice.cpp \
    Calibration/calibration.cpp \
    Calibration/calibrationmeasurement.cpp \
    Calibration/calkit.cpp \
    Calibration/calkitdialog.cpp \
    Calibration/calstandard.cpp \
    Calibration/manualcalibrationdialog.cpp \
    CustomWidgets/colorpickerbutton.cpp \
    CustomWidgets/csvimport.cpp \
    CustomWidgets/informationbox.cpp \
    CustomWidgets/jsonpickerdialog.cpp \
    CustomWidgets/siunitedit.cpp \
    CustomWidgets/tilewidget.cpp \
    CustomWidgets/toggleswitch.cpp \
    CustomWidgets/touchstoneimport.cpp \
    CustomWidgets/tracesetselector.cpp \
    Device/LibreVNA/Compound/compounddevice.cpp \
    Device/LibreVNA/Compound/compounddeviceeditdialog.cpp \
    Device/LibreVNA/Compound/compounddriver.cpp \
    Device/LibreVNA/amplitudecaldialog.cpp \
    Device/LibreVNA/deviceconfigurationdialogv1.cpp \
    Device/LibreVNA/deviceconfigurationdialogvfe.cpp \
    Device/LibreVNA/deviceconfigurationdialogvff.cpp \
    Device/LibreVNA/devicepacketlog.cpp \
    Device/LibreVNA/devicepacketlogview.cpp \
    Device/LibreVNA/firmwareupdatedialog.cpp \
    Device/LibreVNA/frequencycaldialog.cpp \
    Device/LibreVNA/librevnadriver.cpp \
    Device/LibreVNA/librevnatcpdriver.cpp \
    Device/LibreVNA/librevnausbdriver.cpp \
    Device/LibreVNA/manualcontroldialogV1.cpp \
    Device/LibreVNA/manualcontroldialogvfe.cpp \
    Device/LibreVNA/manualcontroldialogvff.cpp \
    Device/LibreVNA/receivercaldialog.cpp \
    Device/LibreVNA/sourcecaldialog.cpp \
    Device/SNA5000A/sna5000adriver.cpp \
    Device/SSA3000X/ssa3000xdriver.cpp \
    Device/devicedriver.cpp \
    Device/devicelog.cpp \
    Device/devicetcpdriver.cpp \
    FieldMeasurement/fieldmeasurement.cpp \
    FieldMeasurement/fieldmeasurementwidget.cpp \
    Generator/generator.cpp \
    Generator/signalgenwidget.cpp \
    SpectrumAnalyzer/spectrumanalyzer.cpp \
    SpectrumAnalyzer/tracewidgetsa.cpp \
    Tools/eseries.cpp \
    Tools/impedancematchdialog.cpp \
    Tools/mixedmodeconversion.cpp \
    Tools/parameters.cpp \
    Traces/Marker/marker.cpp \
    Traces/Marker/markergroup.cpp \
    Traces/Marker/markermodel.cpp \
    Traces/Marker/markerwidget.cpp \
    Traces/Math/dft.cpp \
    Traces/Math/expression.cpp \
    Traces/Math/medianfilter.cpp \
    Traces/Math/parser/mpError.cpp \
    Traces/Math/parser/mpFuncCmplx.cpp \
    Traces/Math/parser/mpFuncCommon.cpp \
    Traces/Math/parser/mpFuncMatrix.cpp \
    Traces/Math/parser/mpFuncNonCmplx.cpp \
    Traces/Math/parser/mpFuncStr.cpp \
    Traces/Math/parser/mpICallback.cpp \
    Traces/Math/parser/mpIOprt.cpp \
    Traces/Math/parser/mpIPackage.cpp \
    Traces/Math/parser/mpIToken.cpp \
    Traces/Math/parser/mpIValReader.cpp \
    Traces/Math/parser/mpIValue.cpp \
    Traces/Math/parser/mpIfThenElse.cpp \
    Traces/Math/parser/mpOprtBinAssign.cpp \
    Traces/Math/parser/mpOprtBinCommon.cpp \
    Traces/Math/parser/mpOprtCmplx.cpp \
    Traces/Math/parser/mpOprtIndex.cpp \
    Traces/Math/parser/mpOprtMatrix.cpp \
    Traces/Math/parser/mpOprtNonCmplx.cpp \
    Traces/Math/parser/mpOprtPostfixCommon.cpp \
    Traces/Math/parser/mpPackageCmplx.cpp \
    Traces/Math/parser/mpPackageCommon.cpp \
    Traces/Math/parser/mpPackageMatrix.cpp \
    Traces/Math/parser/mpPackageNonCmplx.cpp \
    Traces/Math/parser/mpPackageStr.cpp \
    Traces/Math/parser/mpPackageUnit.cpp \
    Traces/Math/parser/mpParser.cpp \
    Traces/Math/parser/mpParserBase.cpp \
    Traces/Math/parser/mpParserMessageProvider.cpp \
    Traces/Math/parser/mpRPN.cpp \
    Traces/Math/parser/mpScriptTokens.cpp \
    Traces/Math/parser/mpTest.cpp \
    Traces/Math/parser/mpTokenReader.cpp \
    Traces/Math/parser/mpValReader.cpp \
    Traces/Math/parser/mpValue.cpp \
    Traces/Math/parser/mpValueCache.cpp \
    Traces/Math/parser/mpVariable.cpp \
    Traces/Math/tdr.cpp \
    Traces/Math/timegate.cpp \
    Traces/Math/tracemath.cpp \
    Traces/Math/windowfunction.cpp \
    Traces/eyediagramplot.cpp \
    Traces/fftcomplex.cpp \
    Traces/sparamtraceselector.cpp \
    Traces/trace.cpp \
    Traces/traceaxis.cpp \
    Traces/tracecsvexport.cpp \
    Traces/traceeditdialog.cpp \
    Traces/traceimportdialog.cpp \
    Traces/tracemodel.cpp \
    Traces/traceplot.cpp \
    Traces/tracesmithchart.cpp \
    Traces/tracepolarchart.cpp \
    Traces/tracetouchstoneexport.cpp \
    Traces/tracewaterfall.cpp \
    Traces/tracewidget.cpp \
    Traces/tracexyplot.cpp \
    Traces/tracepolar.cpp \
    Traces/waterfallaxisdialog.cpp \
    Traces/xyplotaxisdialog.cpp \
    Util/prbs.cpp \
    Util/usbinbuffer.cpp \
    Util/util.cpp \
    VNA/Deembedding/deembedding.cpp \
    VNA/Deembedding/deembeddingdialog.cpp \
    VNA/Deembedding/deembeddingoption.cpp \
    VNA/Deembedding/impedancerenormalization.cpp \
    VNA/Deembedding/manualdeembeddingdialog.cpp \
    VNA/Deembedding/matchingnetwork.cpp \
    VNA/Deembedding/portextension.cpp \
    VNA/Deembedding/twothru.cpp \
    VNA/tracewidgetvna.cpp \
    VNA/vna.cpp \
    about.cpp \
    appwindow.cpp \
    averaging.cpp \
    csv.cpp \
    main.cpp \
    modehandler.cpp \
    mode.cpp \
    modewindow.cpp \
    preferences.cpp \
    savable.cpp \
    scpi.cpp \
    streamingserver.cpp \
    tcpserver.cpp \
    touchstone.cpp \
    unit.cpp

LIBS += -lusb-1.0
unix:LIBS += -L/usr/lib/
win32:LIBS += -L"$$_PRO_FILE_PWD_" # Github actions placed libusb here
osx:INCPATH += /usr/local/include
osx:LIBS += -L/usr/local/lib $(shell pkg-config --libs libusb-1.0)

mac{
        QMAKE_EXPORT += PKG_CONFIG_PATH
        PKG_CONFIG_PATH = /opt/homebrew/lib/pkgconfig
        QT_CONFIG -= no-pkg-config
        CONFIG += link_pkgconfig
        #PKGCONFIG += libusb-1.0
        LIBS += -L/opt/homebrew/lib
        INCLUDEPATH += /opt/homebrew/include/libusb-1.0
}

QT += widgets network

FORMS += \
    Calibration/CalStandardLineEditDialog.ui \
    Calibration/CalStandardLoadEditDialog.ui \
    Calibration/CalStandardOpenEditDialog.ui \
    Calibration/CalStandardReflectEditDialog.ui \
    Calibration/CalStandardShortEditDialog.ui \
    Calibration/CalStandardThroughEditDialog.ui \
    Calibration/LibreCAL/librecaldialog.ui \
    Calibration/calibrationdialogui.ui \
    Calibration/calkitdialog.ui \
    Calibration/manualcalibrationdialog.ui \
    CustomWidgets/csvimport.ui \
    CustomWidgets/jsonpickerdialog.ui \
    CustomWidgets/tilewidget.ui \
    CustomWidgets/touchstoneimport.ui \
    Device/LibreVNA/Compound/compounddeviceeditdialog.ui \
    Device/LibreVNA/Compound/compounddriversettingswidget.ui \
    Device/LibreVNA/addamplitudepointsdialog.ui \
    Device/LibreVNA/amplitudecaldialog.ui \
    Device/LibreVNA/automaticamplitudedialog.ui \
    Device/LibreVNA/deviceconfigurationdialogv1.ui \
    Device/LibreVNA/deviceconfigurationdialogvfe.ui \
    Device/LibreVNA/deviceconfigurationdialogvff.ui \
    Device/LibreVNA/devicepacketlogview.ui \
    Device/LibreVNA/firmwareupdatedialog.ui \
    Device/LibreVNA/frequencycaldialog.ui \
    Device/LibreVNA/librevnadriversettingswidget.ui \
    Device/LibreVNA/manualcontroldialogV1.ui \
    Device/LibreVNA/manualcontroldialogvfe.ui \
    Device/LibreVNA/manualcontroldialogvff.ui \
    Device/devicelog.ui \
    Device/devicetcpdriversettings.ui \
    FieldMeasurement/fieldmeasurementwidget.ui \
    Generator/signalgenwidget.ui \
    FieldMeasurement/fieldmeasurementwidget.ui \
    Tools/impedancematchdialog.ui \
    Tools/mixedmodeconversion.ui \
    Traces/Marker/markerwidget.ui \
    Traces/Math/dftdialog.ui \
    Traces/Math/dftexplanationwidget.ui \
    Traces/Math/expressiondialog.ui \
    Traces/Math/expressionexplanationwidget.ui \
    Traces/Math/medianexplanationwidget.ui \
    Traces/Math/medianfilterdialog.ui \
    Traces/Math/newtracemathdialog.ui \
    Traces/Math/tdrdialog.ui \
    Traces/Math/tdrexplanationwidget.ui \
    Traces/Math/timedomaingatingexplanationwidget.ui \
    Traces/Math/timegatedialog.ui \
    Traces/Math/timegateexplanationwidget.ui \
    Traces/XYPlotConstantLineEditDialog.ui \
    Traces/eyediagrameditdialog.ui \
    Traces/smithchartdialog.ui \
    Traces/polarchartdialog.ui \
    Traces/tracecsvexport.ui \
    Traces/traceeditdialog.ui \
    Traces/traceimportdialog.ui \
    Traces/tracetouchstoneexport.ui \
    Traces/tracewidget.ui \
    Traces/waterfallaxisdialog.ui \
    Traces/xyplotaxisdialog.ui \
    VNA/Deembedding/deembeddingdialog.ui \
    VNA/Deembedding/impedancenormalizationdialog.ui \
    VNA/Deembedding/manualdeembeddingdialog.ui \
    VNA/Deembedding/matchingnetworkdialog.ui \
    VNA/Deembedding/measurementdialog.ui \
    VNA/Deembedding/portextensioneditdialog.ui \
    VNA/Deembedding/twothrudialog.ui \
    VNA/s2pImportOptions.ui \
    aboutdialog.ui \
    main.ui \
    preferencesdialog.ui

DISTFILES += \
    fixMacDylibs.sh \
    icons/DUT.png \
    icons/DUT.svg \
    icons/DUT_onePort.png \
    icons/LibreVNAV1.svg \
    icons/add.png \
    icons/cancel.png \
    icons/chainlink.png \
    icons/clear.png \
    icons/close.svg \
    icons/compound_V1_Ref_Left.png \
    icons/compound_V1_Ref_Left.svg \
    icons/compound_V1_Ref_Middle.png \
    icons/compound_V1_Ref_Middle.svg \
    icons/compound_V1_Ref_Right.png \
    icons/compound_V1_Ref_Right.svg \
    icons/compound_V1_USB.png \
    icons/compound_V1_USB.svg \
    icons/deembedding_disabled.svg \
    icons/deembedding_enabled.svg \
    icons/definedShunt.png \
    icons/definedShunt.svg \
    icons/definedThrough.png \
    icons/definedThrough.svg \
    icons/down.png \
    icons/edit.png \
    icons/export.png \
    icons/horizontal.svg \
    icons/import.png \
    icons/invisible.svg \
    icons/math_disabled.svg \
    icons/math_enabled.svg \
    icons/ok.png \
    icons/open.png \
    icons/pCsC.png \
    icons/pCsC_small.png \
    icons/pCsL.png \
    icons/pCsL_small.png \
    icons/pLsC.png \
    icons/pLsC_small.png \
    icons/pLsL.png \
    icons/pLsL_small.png \
    icons/parallelC.png \
    icons/parallelC.svg \
    icons/parallelL.png \
    icons/parallelL.svg \
    icons/parallelR.png \
    icons/parallelR.svg \
    icons/pause.svg \
    icons/play.png \
    icons/play.svg \
    icons/plus.svg \
    icons/port.png \
    icons/port1.png \
    icons/port1.svg \
    icons/port2.png \
    icons/port2.svg \
    icons/refresh.png \
    icons/remove.png \
    icons/sCpC.png \
    icons/sCpC_small.png \
    icons/sCpL.png \
    icons/sCpL_small.png \
    icons/sLpC.png \
    icons/sLpC_small.png \
    icons/sLpL.png \
    icons/sLpL_small.png \
    icons/save.png \
    icons/seriesC.png \
    icons/seriesC.svg \
    icons/seriesL.png \
    icons/seriesL.svg \
    icons/seriesR.png \
    icons/seriesR.svg \
    icons/trash.png \
    icons/up.png \
    icons/vertical.svg \
    icons/visible.svg \
    icons/zoom-fit.png \
    icons/zoom-in.png \
    icons/zoom-out.png \
    resources/banner.png \
    resources/librevna.desktop \
    resources/librevna.png \
    resources/librevna.svg

RESOURCES += \
    icons.qrc \
    icons.qrc \
    resources.qrc \
    resources/librevna.qrc \
    resources/librevna.qrc

QMAKE_CXXFLAGS += -Wno-deprecated -Wno-deprecated-declarations -Wno-deprecated-copy

CONFIG += c++17
REVISION = $$system(git rev-parse HEAD)
DEFINES += GITHASH=\\"\"$$REVISION\\"\"
DEFINES += FW_MAJOR=1 FW_MINOR=6 FW_PATCH=1 FW_SUFFIX=""
DEFINES -= _UNICODE UNICODE
